name: Build Linux ARM64 Desktop Natives

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build Linux ARM64 natives
      uses: ./.github/actions/build-linux-natives
      with:
        arch: arm64
        docker-image: debian:bookworm
        build-command: |
          apt-get update && apt-get install -y \
              crossbuild-essential-arm64 \
              mesa-common-dev:arm64 libxxf86vm-dev:arm64 \
              libxrandr-dev:arm64 libx11-dev:arm64 \
              zlib1g:arm64
          ./gradlew jnigen jnigenBuildLinuxARM64

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64-natives
        path: |
          libgdx/jnigen-build/libs/linux/arm64/*
          extensions/gdx-bullet/jnigen-build/libs/linux/arm64/*
