name: Build Linux ARM64 Natives (Bookworm)
on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
      options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU ARM64
      uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - name: Install build dependencies
      run: |
        apt-get update && apt-get install -y \
            openjdk-17-jdk \
            crossbuild-essential-arm64 \
            mesa-common-dev:arm64 libxxf86vm-dev:arm64 \
            libxrandr-dev:arm64 libx11-dev:arm64 \
            zlib1g:arm64 ccache gradle

    - name: Build Linux ARM64 natives
      run: |
        ./gradlew jnigen jnigenBuildLinuxARM64 \
          -x :android:* \
          -x :tests:gdx-tests-android:* \
          --no-daemon
