name: Build Linux ARM64 Natives (Bookworm)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm  # Native ARM64 runner
    timeout-minutes: 20  # Should complete in 5-10 mins

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build in Debian Bookworm container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .github/docker/Dockerfile
        platforms: linux/arm64
        outputs: type=local,dest=./artifacts

    - name: Verify artifacts
      run: |
        ls -R artifacts  # Debug directory structure

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64-natives
        path: |
          artifacts/gdx/libs/linuxarm64/*
          artifacts/extensions/**/linuxarm64/*
