name: Build Linux ARM64 Natives (Bookworm)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-arm64:
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 20

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Build in Debian Bookworm container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .github/docker/Dockerfile
        platforms: linux/arm64
        outputs: type=local,dest=./artifacts

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-arm64-natives
        path: |
          artifacts/gdx/libs/linuxarm64/*
          artifacts/extensions/gdx-bullet/libs/linuxarm64/*
          artifacts/extensions/gdx-box2d/libs/linuxarm64/*
          artifacts/extensions/gdx-freetype/libs/linuxarm64/*
        include-hidden-files: true  # In case of hidden directories
